const USERS_FETCHED = 'USERS_FETCHED'
const LIST_FETCHED = 'LIST_FETCHED'
const LOADING = 'LOADING'
const CURRENT_PAGE = 'CURRENT_PAGE'
const TOTAL_PAGES = 'TOTAL_PAGES'
const LIST_FILTER = 'LIST_FILTER'
const TAB_SELECTED = 'TAB_SELECTED'
const TAB_SHOWED = 'TAB_SHOWED'
const SELECTED_ROLES = 'SELECTED_ROLES'
const SELECTED_PRIVILEGES = 'SELECTED_PRIVILEGES'
const MULTSELECT_ROLES = 'MULTSELECT_ROLES'
const MULTSELECT_PRIVILEGES = 'MULTSELECT_PRIVILEGES'
const LIST_ROLES            = 'LIST_ROLES' 
const LIST_PRIVILEGES       = 'LIST_PRIVILEGES'

export {USERS_FETCHED,
        LOADING,
        CURRENT_PAGE,
        TOTAL_PAGES,
        LIST_FILTER,
        TAB_SELECTED,
        TAB_SHOWED,
        SELECTED_PRIVILEGES,
        SELECTED_ROLES,
        MULTSELECT_ROLES,
        MULTSELECT_PRIVILEGES,
        LIST_FETCHED,
        LIST_ROLES,
        LIST_PRIVILEGES}